name: Projeto DevOps 

on:
  push:
    branches: 
      - dev
  pull_request:
    branches:
      - test
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3 

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Verificar se o arquivo App.jsx existe 
        run: test -f Front_end/src/App.jsx 

      - name: Instalar dependências do Front-end
        run: |
          cd Front_end
          npm install

      - name: Testar Build do projeto Front-end
        run: |
          cd Front_end
          npm run build