name : Projeto DevOps 

on :
    push :
        branches : 
            - master
    
jobs :
    build :
        runs-on : ubuntu-latest
    
        steps : 
            - name : Checkout code 
              uses : actions/checkout@v2

            - name : Verificar se o arquivo App.jsx existe 
              run:  test -f src/App.jsx 

            - name : faz a intalação do node modules
              run : npm install 

            - name : testar Build do projeto 
              run : npm run build



        